version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: ./node_modules/.bin/gulp deploy:release
      - run: ./scripts/sentry_release.sh
    branches:
      only:
        - release/0.10.0
        - release/0.11.0
